pr: ["master"]

jobs:
  - job: tests
    displayName: "Tests"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: stable
      - template: ci/install-cargo-readme.yml
      - bash: |
          set -ex
          export RUST_BACKTRACE=1
          cargo test
          cargo test --features "collections"
        displayName: "Run `cargo test`"
      - bash: |
          set -ex
          sudo apt install valgrind
        displayName: "Install Valgrind"
      - bash: |
          set -ex
          export RUST_BACKTRACE=1
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER=valgrind
          cargo test
          cargo test --features "collections"
        displayName: "Run `cargo test` under Valgrind"
  - job: tests_nightly
    displayName: "Tests (Nightly)"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: nightly
      - template: ci/install-cargo-readme.yml
      - bash: |
          set -ex
          export RUST_BACKTRACE=1
          cargo test
          cargo test --features "collections nightly"
        displayName: "Run `cargo test`"
      - bash: |
          set -ex
          sudo apt install valgrind
        displayName: "Install Valgrind"
      - bash: |
          set -ex
          export RUST_BACKTRACE=1
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER=valgrind
          cargo test
          cargo test --features "collections nightly"
        displayName: "Run `cargo test` under Valgrind"
  - job: check_benches
    displayName: "Check that benches build"
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: stable
      - bash: |
          set -ex
          cargo check --benches --features "collections"
        displayName: "Run cargo check"
